### ISSUE TITLE
What's `model.hparams['data']['pose']` ? 

### ISSUE THREAD

**Issue by DeepDuke** [PRBonn/LocNDF#5]
I trained a  model using a set of pcds. But my model seems doesn't contain   `model.hparams['data']['pose']` when perform pose_tracking :
```
Traceback (most recent call last):
  File "/home/spacex/Data/noetic_cudagl_workspace/Study/LocNDF/scripts_pose_tracking/pose_tracking.py", line 99, in <module>
    main()
  File "/home/spacex/Data/noetic_cudagl_workspace/Study/anaconda3/envs/locndf/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/spacex/Data/noetic_cudagl_workspace/Study/anaconda3/envs/locndf/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/spacex/Data/noetic_cudagl_workspace/Study/anaconda3/envs/locndf/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/spacex/Data/noetic_cudagl_workspace/Study/anaconda3/envs/locndf/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/spacex/Data/noetic_cudagl_workspace/Study/LocNDF/scripts_pose_tracking/pose_tracking.py", line 59, in main
    tracker = registration.PoseTracker(
  File "/home/spacex/Data/noetic_cudagl_workspace/Study/LocNDF/src/loc_ndf/utils/registration.py", line 32, in __init__
    model.hparams['data']['pose'], device=self.device, dtype=torch.double).reshape(4, 4)
KeyError: 'pose'

```

**Comment by Lee-JaeWon** [comment]
@DeepDuke When i run this code, that problem should not occur if you have operated the `pose_tracking.py` using the appropriate .ckpt (learned) path.
Tell me exactly how you did it.

**Comment by louis-wiesmann** [comment]
@DeepDuke You have to add the pose to the config dict, I am doing it [here](https://github.com/PRBonn/LocNDF/blob/main/scripts_pose_tracking/train_mapping.py#L40) for example. It is needed since the submaps are in a local coordinate system. Please let me know if you need more instructions.
